### ISSUE TITLE
image

### ISSUE THREAD

**Issue by Roboxkin** [Imagick/ImagickDemos#94]
Reported from Imagick::blackThresholdImage

$image_path = $_SERVER['DOCUMENT_ROOT'].'/1.png';
$thresholdColor = 20;

function blackThresholdImage($image_path, $thresholdColor){
    $image = new \Imagick(realpath($image_path));
    $image->blackthresholdimage($thresholdColor);
    header("Content-Type: image/png");
    echo $image;
}

P.S. Could you at least give an elementary example.

**Comment by Danack** [comment]
Sorry, I have no idea what you are asking.

There is an example on that page, that allows you to play with the value color e.g. https://phpimagick.com/Imagick/blackThresholdImage?threshold_color=rgb(53%2C%20136%2C%2038)&image_path=Lorikeet


The threshold colour is literally a string:

```
$thresholdColor = "rgb(53, 136, 38)";
```

**Comment by Danack** [comment]
Going to close as still no idea.
