### ISSUE TITLE
Imagick::unsharpMaskImage page error

### ISSUE THREAD

**Issue by springknees** [Imagick/ImagickDemos#98]
Hi FYI

If a value that is not a whole number is entered in the Amount field of the Imagick::unsharpMaskImage page, the page breaks! You can see the result here...

[https://phpimagick.com/Imagick/unsharpMaskImage?radius=5&sigma=1&amount=4.5&unsharp_threshold=0&channel=All&image_path=Lorikeet](url)

Regards Springknees

**Comment by Danack** [comment]
Thanks. Fixed now.
